# build.ps1 - M110A Modem Build Script with Version Management
# Usage: .\build.ps1 [-Target <server|test|all>] [-Increment <major|minor|patch>] [-Clean]

param(
    [string]$Target = "all",
    [string]$Increment = "",
    [switch]$Clean = $false
)

$ErrorActionPreference = "Stop"
$ProjectRoot = $PSScriptRoot
$VersionFile = Join-Path $ProjectRoot "api\version.h"

# ============================================================
# Version Management
# ============================================================

function Get-CurrentVersion {
    if (-not (Test-Path $VersionFile)) {
        return @{ Major = 1; Minor = 0; Patch = 0; Build = 0 }
    }
    
    $content = Get-Content $VersionFile -Raw
    $major = if ($content -match 'VERSION_MAJOR = (\d+)') { [int]$Matches[1] } else { 1 }
    $minor = if ($content -match 'VERSION_MINOR = (\d+)') { [int]$Matches[1] } else { 0 }
    $patch = if ($content -match 'VERSION_PATCH = (\d+)') { [int]$Matches[1] } else { 0 }
    $build = if ($content -match 'BUILD_NUMBER = (\d+)') { [int]$Matches[1] } else { 0 }
    
    return @{ Major = $major; Minor = $minor; Patch = $patch; Build = $build }
}

function Update-Version {
    param($Version, $IncrementType)
    
    switch ($IncrementType) {
        "major" { 
            $Version.Major++
            $Version.Minor = 0
            $Version.Patch = 0
        }
        "minor" {
            $Version.Minor++
            $Version.Patch = 0
        }
        "patch" {
            $Version.Patch++
        }
    }
    
    # Always increment build number
    $Version.Build++
    
    return $Version
}

function Write-VersionHeader {
    param($Version)
    
    # Get git info
    $gitCommit = (git rev-parse --short HEAD 2>$null) -replace '\s',''
    if (-not $gitCommit) { $gitCommit = "unknown" }
    
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null) -replace '\s',''
    if (-not $gitBranch) { $gitBranch = "unknown" }
    
    $buildDate = Get-Date -Format "yyyy-MM-dd"
    $buildTime = Get-Date -Format "HH:mm:ss"
    
    $header = @"
/**
 * @file version.h
 * @brief Auto-generated version information
 * 
 * DO NOT EDIT MANUALLY - Generated by build.ps1
 */

#ifndef M110A_VERSION_H
#define M110A_VERSION_H

#include <string>

namespace m110a {

// Semantic version
constexpr int VERSION_MAJOR = $($Version.Major);
constexpr int VERSION_MINOR = $($Version.Minor);
constexpr int VERSION_PATCH = $($Version.Patch);

// Build information (auto-generated)
constexpr int BUILD_NUMBER = $($Version.Build);
constexpr const char* GIT_COMMIT = "$gitCommit";
constexpr const char* GIT_BRANCH = "$gitBranch";
constexpr const char* BUILD_DATE = "$buildDate";
constexpr const char* BUILD_TIME = "$buildTime";

/// Get version string (e.g., "1.2.0")
inline std::string version() {
    return std::to_string(VERSION_MAJOR) + "." +
           std::to_string(VERSION_MINOR) + "." +
           std::to_string(VERSION_PATCH);
}

/// Get full version string with build info (e.g., "1.2.0+build.1.b52efc3")
inline std::string version_full() {
    return version() + "+build." + std::to_string(BUILD_NUMBER) + "." + GIT_COMMIT;
}

/// Get build info string
inline std::string build_info() {
    return std::string("Build ") + std::to_string(BUILD_NUMBER) + 
           " (" + GIT_COMMIT + ") " + BUILD_DATE + " " + BUILD_TIME;
}

} // namespace m110a

#endif // M110A_VERSION_H
"@
    
    Set-Content -Path $VersionFile -Value $header -NoNewline
    Write-Host "Version: $($Version.Major).$($Version.Minor).$($Version.Patch)+build.$($Version.Build).$gitCommit" -ForegroundColor Cyan
}

# ============================================================
# Build Functions
# ============================================================

$CXX = "g++"
$CXXFLAGS = "-std=c++17 -O2 -I. -Isrc -D_USE_MATH_DEFINES"
$LDFLAGS = "-lws2_32"

function Build-Server {
    Write-Host "`n=== Building Server ===" -ForegroundColor Yellow
    
    # Kill existing server
    Get-Process m110a_server -ErrorAction SilentlyContinue | Stop-Process -Force
    Start-Sleep -Milliseconds 500
    
    $sources = @(
        "server/main.cpp",
        "server/msdmt_server.cpp",
        "api/modem_tx.cpp",
        "api/modem_rx.cpp"
    )
    
    $cmd = "$CXX $CXXFLAGS -o server/m110a_server.exe $($sources -join ' ') $LDFLAGS"
    Write-Host $cmd -ForegroundColor DarkGray
    
    Invoke-Expression $cmd
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Server built successfully" -ForegroundColor Green
    } else {
        throw "Server build failed"
    }
}

function Build-ExhaustiveTest {
    Write-Host "`n=== Building Exhaustive Test ===" -ForegroundColor Yellow
    
    $cmd = "$CXX $CXXFLAGS -o server/exhaustive_server_test.exe server/exhaustive_server_test.cpp $LDFLAGS"
    Write-Host $cmd -ForegroundColor DarkGray
    
    Invoke-Expression $cmd
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Exhaustive test built successfully" -ForegroundColor Green
    } else {
        throw "Exhaustive test build failed"
    }
}

function Build-UnifiedTest {
    Write-Host "`n=== Building Unified Exhaustive Test ===" -ForegroundColor Yellow
    
    $sources = @(
        "test/exhaustive_test_unified.cpp",
        "api/modem_tx.cpp",
        "api/modem_rx.cpp"
    )
    
    $cmd = "$CXX $CXXFLAGS -o test/exhaustive_test.exe $($sources -join ' ') $LDFLAGS"
    Write-Host $cmd -ForegroundColor DarkGray
    
    Invoke-Expression $cmd
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "Unified test built successfully" -ForegroundColor Green
    } else {
        throw "Unified test build failed"
    }
}

function Clean-Build {
    Write-Host "`n=== Cleaning ===" -ForegroundColor Yellow
    
    $exeFiles = Get-ChildItem -Path $ProjectRoot -Recurse -Include "*.exe" -ErrorAction SilentlyContinue
    foreach ($exe in $exeFiles) {
        Remove-Item $exe.FullName -Force -ErrorAction SilentlyContinue
        Write-Host "Removed: $($exe.Name)" -ForegroundColor DarkGray
    }
}

# ============================================================
# Main
# ============================================================

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "M110A Modem Build System" -ForegroundColor Cyan  
Write-Host "============================================" -ForegroundColor Cyan

Set-Location $ProjectRoot

# Clean if requested
if ($Clean) {
    Clean-Build
}

# Update version
$version = Get-CurrentVersion
$version = Update-Version -Version $version -IncrementType $Increment
Write-VersionHeader -Version $version

# Build targets
switch ($Target.ToLower()) {
    "server" {
        Build-Server
    }
    "test" {
        Build-ExhaustiveTest
    }
    "unified" {
        Build-UnifiedTest
    }
    "all" {
        Build-Server
        Build-ExhaustiveTest
        Build-UnifiedTest
    }
    default {
        Write-Host "Unknown target: $Target" -ForegroundColor Red
        Write-Host "Valid targets: server, test, unified, all" -ForegroundColor Yellow
        exit 1
    }
}

Write-Host "`n============================================" -ForegroundColor Cyan
Write-Host "Build Complete" -ForegroundColor Green
Write-Host "============================================" -ForegroundColor Cyan
