# build.ps1 - M110A Modem Build Script
# 
# Usage: .\build.ps1 [-Increment <major|minor|patch>] [-Clean]
#
# All executables output to release/bin/
#
# ============================================================
# FROZEN BLOCK: Parameters - DO NOT MODIFY WITHOUT PERMISSION
# ============================================================

param(
    [string]$Increment = "",
    [string]$Target = "",
    [switch]$Clean = $false,
    [switch]$Help = $false
)

$ErrorActionPreference = "Stop"
$ProjectRoot = $PSScriptRoot
$VersionFile = Join-Path $ProjectRoot "api\version.h"
$ReleaseBin = Join-Path $ProjectRoot "release\bin"

# ============================================================
# FROZEN BLOCK: Help Text - DO NOT MODIFY WITHOUT PERMISSION
# ============================================================

if ($Help) {
    Write-Host @"
M110A Modem Build Script
========================

USAGE:
    .\build.ps1 [options]

OPTIONS:
    -Increment <type>     Version increment: major, minor, patch
    -Target <name>        Build only specified target (m110a_server, test_gui, hfchansim)
    -Clean                Clean release/bin/ before building
    -Help                 Show this help message

OUTPUT:
    All executables are built to release/bin/
"@
    exit 0
}

# ============================================================
# FROZEN BLOCK: Version Management - DO NOT MODIFY WITHOUT PERMISSION
# These functions read/write api/version.h which is used by ALL executables
# ============================================================

function Get-CurrentVersion {
    if (-not (Test-Path $VersionFile)) {
        return @{ Major = 1; Minor = 0; Patch = 0; Build = 0; Prerelease = "" }
    }
    
    $content = Get-Content $VersionFile -Raw
    $major = if ($content -match 'VERSION_MAJOR = (\d+)') { [int]$Matches[1] } else { 1 }
    $minor = if ($content -match 'VERSION_MINOR = (\d+)') { [int]$Matches[1] } else { 0 }
    $patch = if ($content -match 'VERSION_PATCH = (\d+)') { [int]$Matches[1] } else { 0 }
    $build = if ($content -match 'BUILD_NUMBER = (\d+)') { [int]$Matches[1] } else { 0 }
    $prerelease = if ($content -match 'VERSION_PRERELEASE = "([^"]*)"') { $Matches[1] } else { "" }
    
    return @{ Major = $major; Minor = $minor; Patch = $patch; Build = $build; Prerelease = $prerelease }
}

function Get-VersionString {
    param($Version)
    $base = "v$($Version.Major).$($Version.Minor).$($Version.Patch)"
    if ($Version.Prerelease) { $base += "-$($Version.Prerelease)" }
    return $base
}

function Update-Version {
    param($Version, $IncrementType)
    
    switch ($IncrementType) {
        "major" { $Version.Major++; $Version.Minor = 0; $Version.Patch = 0; $Version.Prerelease = "" }
        "minor" { $Version.Minor++; $Version.Patch = 0; $Version.Prerelease = "" }
        "patch" { $Version.Patch++; $Version.Prerelease = "" }
    }
    
    $Version.Build++
    return $Version
}

# ============================================================
# FROZEN BLOCK: version.h Generation - DO NOT MODIFY WITHOUT PERMISSION
# This header is #included by all executables for consistent versioning
# ============================================================

function Write-VersionHeader {
    param($Version)
    
    $gitCommit = (git rev-parse --short HEAD 2>$null) -replace '\s',''
    if (-not $gitCommit) { $gitCommit = "unknown" }
    
    $gitBranch = (git rev-parse --abbrev-ref HEAD 2>$null) -replace '\s',''
    if (-not $gitBranch) { $gitBranch = "unknown" }
    
    $buildDate = Get-Date -Format "yyyy-MM-dd"
    $buildTime = Get-Date -Format "HH:mm:ss"
    
    $header = @"
/**
 * @file version.h
 * @brief Auto-generated version information
 * 
 * M110A Modem - MIL-STD-188-110A Compatible HF Modem
 * Copyright (c) 2024-2025 Alex Pennington
 * DO NOT EDIT MANUALLY - Generated by build.ps1
 */

#ifndef M110A_VERSION_H
#define M110A_VERSION_H

#include <string>

namespace m110a {

constexpr int VERSION_MAJOR = $($Version.Major);
constexpr int VERSION_MINOR = $($Version.Minor);
constexpr int VERSION_PATCH = $($Version.Patch);
constexpr const char* VERSION_PRERELEASE = "$($Version.Prerelease)";
constexpr int BUILD_NUMBER = $($Version.Build);
constexpr const char* GIT_COMMIT = "$gitCommit";
constexpr const char* GIT_BRANCH = "$gitBranch";
constexpr const char* BUILD_DATE = "$buildDate";
constexpr const char* BUILD_TIME = "$buildTime";

inline std::string version() {
    std::string v = std::to_string(VERSION_MAJOR) + "." +
                    std::to_string(VERSION_MINOR) + "." +
                    std::to_string(VERSION_PATCH);
    if (VERSION_PRERELEASE[0] != '\0') { v += "-"; v += VERSION_PRERELEASE; }
    return v;
}

inline std::string version_full() {
    return version() + " (" + GIT_BRANCH + ") build." + std::to_string(BUILD_NUMBER) + "." + GIT_COMMIT;
}

inline std::string build_info() {
    return std::string("Build ") + std::to_string(BUILD_NUMBER) + " (" + GIT_COMMIT + ") " + BUILD_DATE;
}

inline std::string version_short() {
    return "v" + version() + "+" + std::to_string(BUILD_NUMBER);
}

inline std::string version_header() {
    return std::string("M110A Modem v") + version() + " (" + GIT_BRANCH + 
           " branch, build " + std::to_string(BUILD_NUMBER) + ", commit " + GIT_COMMIT + ")";
}

inline std::string copyright_notice() {
    return "Copyright (c) 2024-2025 Alex Pennington\n"
           "Email: alex.pennington@organicengineer.com\n"
           "MIL-STD-188-110A Compatible HF Modem";
}

} // namespace m110a

#endif // M110A_VERSION_H
"@
    
    Set-Content -Path $VersionFile -Value $header -NoNewline
}

# ============================================================
# FROZEN BLOCK: Build Configuration - DO NOT MODIFY WITHOUT PERMISSION
# ============================================================

$CXX = "g++"
$CXXFLAGS = "-std=c++17 -O2 -I. -Isrc -D_USE_MATH_DEFINES"
$LDFLAGS = "-static -lws2_32"

$MODEM_SOURCES = "api/modem_tx.cpp api/modem_rx.cpp"
$PCM_SOURCES = "src/io/pcm_file.cpp"

# brain_core uses prebuilt static library
$BRAIN_INCLUDES = "-Iextern -Iextern/brain_core -Iextern/brain_core/include -Iextern/brain_core/include/m188110a"
$BRAIN_LDFLAGS = "-Lextern/brain_core/lib/win64 -lm188110a"

# ============================================================
# FROZEN BLOCK: Main Build Logic - DO NOT MODIFY WITHOUT PERMISSION
# ============================================================

Write-Host "============================================" -ForegroundColor Cyan
Write-Host "M110A Modem Build" -ForegroundColor Cyan  
Write-Host "============================================" -ForegroundColor Cyan

$buildTimer = [System.Diagnostics.Stopwatch]::StartNew()
Set-Location $ProjectRoot

# Ensure release/bin exists
if (-not (Test-Path $ReleaseBin)) {
    New-Item -ItemType Directory -Path $ReleaseBin -Force | Out-Null
}

if ($Clean) {
    Write-Host "`nCleaning release/bin/..." -ForegroundColor Yellow
    Get-ChildItem -Path $ReleaseBin -Filter "*.exe" -ErrorAction SilentlyContinue | Remove-Item -Force
}

# Update version header
$version = Get-CurrentVersion
$version = Update-Version -Version $version -IncrementType $Increment
$gitCommit = (git rev-parse --short HEAD 2>$null) -replace '\s',''
if (-not $gitCommit) { $gitCommit = "unknown" }
Write-VersionHeader -Version $version

# Display version with build number and commit (matches m110a::version_header() format)
Write-Host "`nVersion: $(Get-VersionString $version) (build $($version.Build), commit $gitCommit)" -ForegroundColor Cyan

# Kill running server
Get-Process m110a_server -ErrorAction SilentlyContinue | Stop-Process -Force
Start-Sleep -Milliseconds 300

# Check for brain_core
$hasBrain = (Test-Path "extern/brain_core/include/m188110a/Cm110s.h") -and (Test-Path "extern/brain_core/lib/win64/libm188110a.a")
if (-not $hasBrain) {
    Write-Host "`nWARNING: brain_core submodule not found or incomplete, skipping Brain targets" -ForegroundColor Yellow
    Write-Host "  Run: git submodule update --init --recursive" -ForegroundColor DarkYellow
}

# ============================================================
# FROZEN BLOCK: Build Targets - DO NOT MODIFY WITHOUT PERMISSION
# To add a new target, get permission first, then add to this array
# All targets must use api/version.h for consistent versioning
# ============================================================

$targets = @(
    # Core server - FROZEN
    @{ Name = "m110a_server"; Cmd = "$CXX $CXXFLAGS -o release/bin/m110a_server.exe server/main.cpp server/tcp_server_base.cpp $MODEM_SOURCES $LDFLAGS" },
    
    # Test GUI - FROZEN  
    @{ Name = "test_gui"; Cmd = "$CXX $CXXFLAGS -o release/bin/test_gui.exe test/test_gui/main.cpp $LDFLAGS -lshell32" },
    
    # HF Channel Simulator - Added 2025-12-12
    @{ Name = "hfchansim"; Cmd = "$CXX $CXXFLAGS -o release/bin/hfchansim.exe hfchansim/main.cpp $LDFLAGS" }
)

# ============================================================
# FROZEN BLOCK: Brain Server Build - DO NOT MODIFY WITHOUT PERMISSION
# ============================================================

if ($hasBrain -and (-not $Target -or $Target -eq "brain_modem_server")) {
    Write-Host "`n=== brain_modem_server ===" -ForegroundColor Yellow
    Push-Location "extern/brain_core"
    try {
        & .\build.ps1 2>&1 | Out-Null
        if (Test-Path "brain_modem_server.exe") {
            Copy-Item "brain_modem_server.exe" "../../release/bin/brain_modem_server.exe" -Force
            Write-Host "  OK" -ForegroundColor Green
        } else {
            Write-Host "  FAILED" -ForegroundColor Red
        }
    } catch {
        Write-Host "  FAILED: $_" -ForegroundColor Red
    }
    Pop-Location
}

# ============================================================
# FROZEN BLOCK: Build Execution - DO NOT MODIFY WITHOUT PERMISSION
# ============================================================

# ============================================================
# FROZEN BLOCK: Target Filtering - DO NOT MODIFY WITHOUT PERMISSION
# ============================================================

# Filter targets if -Target specified
if ($Target) {
    $filtered = $targets | Where-Object { $_.Name -eq $Target }
    if (-not $filtered) {
        Write-Host "Unknown target: $Target" -ForegroundColor Red
        Write-Host "Available targets: $(($targets | ForEach-Object { $_.Name }) -join ', ')" -ForegroundColor Yellow
        exit 1
    }
    $targets = @($filtered)
}

$failed = @()

foreach ($t in $targets) {
    Write-Host "`n=== $($t.Name) ===" -ForegroundColor Yellow
    Write-Host $t.Cmd -ForegroundColor DarkGray
    
    Invoke-Expression $t.Cmd
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "  OK" -ForegroundColor Green
    } else {
        Write-Host "  FAILED" -ForegroundColor Red
        $failed += $t.Name
    }
}

$buildTimer.Stop()

# ============================================================
# FROZEN BLOCK: Build Summary - DO NOT MODIFY WITHOUT PERMISSION
# ============================================================

Write-Host "`n============================================" -ForegroundColor Cyan
if ($failed.Count -eq 0) {
    Write-Host "Build Complete - $($buildTimer.Elapsed.TotalSeconds.ToString('0.0'))s" -ForegroundColor Green
} else {
    Write-Host "Build Failed: $($failed -join ', ')" -ForegroundColor Red
}
Write-Host "Output: release/bin/" -ForegroundColor Yellow
Write-Host "============================================" -ForegroundColor Cyan

Write-Host ""
Write-Host "TO TRIGGER GITHUB RELEASE:" -ForegroundColor Magenta
Write-Host "  .\build.ps1 -Increment patch" -ForegroundColor White
Write-Host "  git add -A" -ForegroundColor White
Write-Host "  git commit -m 'Release: <description>'" -ForegroundColor White
Write-Host "  git push origin master" -ForegroundColor White
Write-Host ""
