/**
 * @file version.h
 * @brief Auto-generated version information
 * 
 * DO NOT EDIT MANUALLY - Generated by build.ps1
 */

#ifndef M110A_VERSION_H
#define M110A_VERSION_H

#include <string>

namespace m110a {

// Semantic version
constexpr int VERSION_MAJOR = 1;
constexpr int VERSION_MINOR = 2;
constexpr int VERSION_PATCH = 0;

// Build information (auto-generated)
constexpr int BUILD_NUMBER = 36;
constexpr const char* GIT_COMMIT = "baec8c0";
constexpr const char* GIT_BRANCH = "master";
constexpr const char* BUILD_DATE = "2025-12-08";
constexpr const char* BUILD_TIME = "00:54:51";

/// Get version string (e.g., "1.2.0")
inline std::string version() {
    return std::to_string(VERSION_MAJOR) + "." +
           std::to_string(VERSION_MINOR) + "." +
           std::to_string(VERSION_PATCH);
}

/// Get full version string with build info (e.g., "1.2.0+build.1.b52efc3")
inline std::string version_full() {
    return version() + "+build." + std::to_string(BUILD_NUMBER) + "." + GIT_COMMIT;
}

/// Get build info string
inline std::string build_info() {
    return std::string("Build ") + std::to_string(BUILD_NUMBER) + 
           " (" + GIT_COMMIT + ") " + BUILD_DATE + " " + BUILD_TIME;
}

} // namespace m110a

#endif // M110A_VERSION_H