/**
 * @file version.h
 * @brief Auto-generated version information
 * 
 * M110A Modem - MIL-STD-188-110A Compatible HF Modem
 * Copyright (c) 2024-2025 Alex Pennington
 * Email: alex.pennington@organicengineer.com
 * 
 * DO NOT EDIT MANUALLY - Generated by build.ps1
 */

#ifndef M110A_VERSION_H
#define M110A_VERSION_H

#include <string>

namespace m110a {

// Semantic version
constexpr int VERSION_MAJOR = 1;
constexpr int VERSION_MINOR = 2;
constexpr int VERSION_PATCH = 0;

// Build information (auto-generated)
constexpr int BUILD_NUMBER = 199;
constexpr const char* GIT_COMMIT = "a5f96a3";
constexpr const char* GIT_BRANCH = "turbo";
constexpr const char* BUILD_DATE = "2025-12-10";
constexpr const char* BUILD_TIME = "01:31:55";

/// Get version string (e.g., "1.2.0")
inline std::string version() {
    return std::to_string(VERSION_MAJOR) + "." +
           std::to_string(VERSION_MINOR) + "." +
           std::to_string(VERSION_PATCH);
}

/// Get full version string with branch and build info
/// Format: "1.2.0 (turbo) build.42.abc1234"
inline std::string version_full() {
    return version() + " (" + GIT_BRANCH + ") build." + 
           std::to_string(BUILD_NUMBER) + "." + GIT_COMMIT;
}

/// Get build info string for reports
/// Format: "Build 42 (abc1234) turbo 2025-12-08 07:30:00"
inline std::string build_info() {
    return std::string("Build ") + std::to_string(BUILD_NUMBER) + 
           " (" + GIT_COMMIT + ") " + GIT_BRANCH + " " + BUILD_DATE + " " + BUILD_TIME;
}

/// Get version for help/usage display
/// Format: "v1.2.0-turbo+42"
inline std::string version_short() {
    return "v" + version() + "-" + GIT_BRANCH + "+" + std::to_string(BUILD_NUMBER);
}

/// Get detailed version info for headers
/// Format: "M110A Modem v1.2.0 (turbo branch, build 42, commit abc1234)"
inline std::string version_header() {
    return std::string("M110A Modem v") + version() + " (" + GIT_BRANCH + 
           " branch, build " + std::to_string(BUILD_NUMBER) + ", commit " + GIT_COMMIT + ")";
}

/// Get copyright notice
inline std::string copyright_notice() {
    return "Copyright (c) 2024-2025 Alex Pennington\n"
           "Email: alex.pennington@organicengineer.com\n"
           "MIL-STD-188-110A Compatible HF Modem";
}

/// Get EULA acceptance notice
inline std::string eula_notice() {
    return "By using this software, you agree to the End User License Agreement.\n"
           "See EULA.md for complete terms and conditions.\n"
           "License required - Contact: alex.pennington@organicengineer.com";
}

} // namespace m110a

#endif // M110A_VERSION_H