/**
 * @file version.h
 * @brief Auto-generated version information
 * 
 * M110A Modem - MIL-STD-188-110A Compatible HF Modem
 * Copyright (c) 2024-2025 Alex Pennington
 * Email: alex.pennington@organicengineer.com
 * 
 * DO NOT EDIT MANUALLY - Generated by build.ps1
 */

#ifndef M110A_VERSION_H
#define M110A_VERSION_H

#include <string>

namespace m110a {

// Semantic version
constexpr int VERSION_MAJOR = 1;
constexpr int VERSION_MINOR = 3;
constexpr int VERSION_PATCH = 12;

// Prerelease tag (empty for stable releases)
constexpr const char* VERSION_PRERELEASE = "";

// Build information (auto-generated)
constexpr int BUILD_NUMBER = 275;
constexpr const char* GIT_COMMIT = "958884f";
constexpr const char* GIT_BRANCH = "master";
constexpr const char* BUILD_DATE = "2025-12-11";
constexpr const char* BUILD_TIME = "00:34:00";

/// Get version string (e.g., "1.2.0" or "1.2.0-rc.1")
inline std::string version() {
    std::string v = std::to_string(VERSION_MAJOR) + "." +
                    std::to_string(VERSION_MINOR) + "." +
                    std::to_string(VERSION_PATCH);
    if (VERSION_PRERELEASE[0] != '\0') {
        v += "-";
        v += VERSION_PRERELEASE;
    }
    return v;
}

/// Get full version string with branch and build info
inline std::string version_full() {
    return version() + " (" + GIT_BRANCH + ") build." + 
           std::to_string(BUILD_NUMBER) + "." + GIT_COMMIT;
}

/// Get build info string for reports
inline std::string build_info() {
    return std::string("Build ") + std::to_string(BUILD_NUMBER) + 
           " (" + GIT_COMMIT + ") " + GIT_BRANCH + " " + BUILD_DATE + " " + BUILD_TIME;
}

/// Get version for help/usage display
inline std::string version_short() {
    return "v" + version() + "-" + GIT_BRANCH + "+" + std::to_string(BUILD_NUMBER);
}

/// Get detailed version info for headers
inline std::string version_header() {
    return std::string("M110A Modem v") + version() + " (" + GIT_BRANCH + 
           " branch, build " + std::to_string(BUILD_NUMBER) + ", commit " + GIT_COMMIT + ")";
}

/// Get copyright notice
inline std::string copyright_notice() {
    return "Copyright (c) 2024-2025 Alex Pennington\n"
           "Email: alex.pennington@organicengineer.com\n"
           "MIL-STD-188-110A Compatible HF Modem";
}

} // namespace m110a

#endif // M110A_VERSION_H